### ISSUE TITLE
Support tuples as return types

### ISSUE THREAD

**Issue by Feliix42** [ohua-dev/ohuac#2]
While working on ohua-dev/ohua-rust-runtime#7, I noticed that the following dummy `ohuac` file does not compile

```rust
ns some_ns;

use sf tuples (append_to_string, extend_string, output_values);

fn main(input_number: i32, input_string: String) -> (i32, String, usize) {
    let intermediate = append_to_string(input_string, input_number);
    let extended = extend_string(intermediate);
    output_values(input_number, extended)
}
```

indicating that tuples are not supported by ohuac right now. As returning tuples is not that uncommon I would love seeing them added.

**Comment by JustusAdam** [comment]
I am not sure why that fails. Tuples should be supported in any place that accepts a type annotation, including return annotations.

**Comment by JustusAdam** [comment]
Is your compiler on the newest version? You should check that your stack.yaml in ohuac mentions the clike-parser in a decently recent version. Otherwise you probably should pull ohuac again

**Comment by JustusAdam** [comment]
I have tested your example as well now, and it parses correctly.

**Comment by Feliix42** [comment]
🤦‍♂️ 
All good, the most obvious step is most often times the one I forget about. Sorry for the interruption.

**Comment by JustusAdam** [comment]
It's okay. Happens to everyone 😉
